#!/usr/bin/env bash
#Configures an Ubuntu server:
#  - localhost resolves to 127.0.0.2
#  - facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bak
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
echo '8.8.8.8 facebook.com' >> /etc/hosts
echo "Success"
cat /etc/hosts
